name: moviebook
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  wiredash: ^1.7.4
  hive: ^2.2.3
  path_provider: ^2.1.1
  flare_flutter: ^3.0.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/languages/
    - assets/animations/
